name: Codecov coverage

on: [push,pull_request]

env:
  COMPILER: g++-6 
  VARIANT: debug 
  TOOLSET: gcc 
  CXXSTD: 11 
  B2_OPTIONS: "coverage=on"
  LIBRARY: gil

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out our repository

    - name: Setup Boost
      run: |
        REF=${GITHUB_BASE_REF:-$GITHUB_REF}
        BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
        cd ..
        git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
        echo "ls starts"
        ls
        echo "ls ended"
        cd boost-root
        cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
        git submodule update --init tools/boostdep
        python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
        ./bootstrap.sh
        ./b2 -d0 headers
        cd boost-root
        export BOOST_ROOT=$(pwd)
        ./bootstrap.sh
        ls
        echo "I was here"
      
    - name: Install required packages 
      run: |
          sudo apt-get install libpng-dev
          sudo apt-get install libjpeg-dev
          sudo apt-get install libtiff5-dev
          sudo apt-get install libraw-dev
          sudo apt-get install lcov
          bash .ci/coverage.sh