name: Codecov coverage

on: [push,pull_request]

env:
  COMPILER: g++-6 
  VARIANT: debug 
  TOOLSET: gcc 
  CXXSTD: 11 
  B2_OPTIONS: "coverage=on"
  LIBRARY: gil
  UBSAN_OPTIONS: print_stacktrace=1


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Setup Boost
      run: |
        REF=${GITHUB_BASE_REF:-$GITHUB_REF}
        BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
        cd ..
        git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
        git submodule update --init tools/boostdep
        python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
        ./bootstrap.sh
        ./b2 -d0 headers

    - name: Get doc related files
      run: |
        pip3 --version
        pip3 install --upgrade pip
        pip3 install --user sphinx>=2.1
        
    
    - name: Doc upload
      run: |
        export ${{ secrets.GITHUB_TOKEN }}
        ls
        bash .ci/upload_docs.sh